/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProfileIdProfileRouteImport } from './routes/p/$profileId/_profile'
import { Route as PProfileIdProfileIndexRouteImport } from './routes/p/$profileId/_profile/index'
import { Route as PProfileIdProfileTransactionsIndexRouteImport } from './routes/p/$profileId/_profile/transactions/index'
import { Route as PProfileIdProfileSettingsIndexRouteImport } from './routes/p/$profileId/_profile/settings/index'
import { Route as PProfileIdProfileChartsIndexRouteImport } from './routes/p/$profileId/_profile/charts/index'
import { Route as PProfileIdProfileAccountsIndexRouteImport } from './routes/p/$profileId/_profile/accounts/index'
import { Route as PProfileIdProfileSettingsTransactionCategoriesRouteImport } from './routes/p/$profileId/_profile/settings/transaction-categories'
import { Route as PProfileIdProfileSettingsSymbolsRouteImport } from './routes/p/$profileId/_profile/settings/symbols'
import { Route as PProfileIdProfileSettingsBackupRouteImport } from './routes/p/$profileId/_profile/settings/backup'

const PProfileIdRouteImport = createFileRoute('/p/$profileId')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProfileIdRoute = PProfileIdRouteImport.update({
  id: '/p/$profileId',
  path: '/p/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProfileIdProfileRoute = PProfileIdProfileRouteImport.update({
  id: '/_profile',
  getParentRoute: () => PProfileIdRoute,
} as any)
const PProfileIdProfileIndexRoute = PProfileIdProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProfileIdProfileRoute,
} as any)
const PProfileIdProfileTransactionsIndexRoute =
  PProfileIdProfileTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)
const PProfileIdProfileSettingsIndexRoute =
  PProfileIdProfileSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)
const PProfileIdProfileChartsIndexRoute =
  PProfileIdProfileChartsIndexRouteImport.update({
    id: '/charts/',
    path: '/charts/',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)
const PProfileIdProfileAccountsIndexRoute =
  PProfileIdProfileAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)
const PProfileIdProfileSettingsTransactionCategoriesRoute =
  PProfileIdProfileSettingsTransactionCategoriesRouteImport.update({
    id: '/settings/transaction-categories',
    path: '/settings/transaction-categories',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)
const PProfileIdProfileSettingsSymbolsRoute =
  PProfileIdProfileSettingsSymbolsRouteImport.update({
    id: '/settings/symbols',
    path: '/settings/symbols',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)
const PProfileIdProfileSettingsBackupRoute =
  PProfileIdProfileSettingsBackupRouteImport.update({
    id: '/settings/backup',
    path: '/settings/backup',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$profileId': typeof PProfileIdProfileRouteWithChildren
  '/p/$profileId/': typeof PProfileIdProfileIndexRoute
  '/p/$profileId/settings/backup': typeof PProfileIdProfileSettingsBackupRoute
  '/p/$profileId/settings/symbols': typeof PProfileIdProfileSettingsSymbolsRoute
  '/p/$profileId/settings/transaction-categories': typeof PProfileIdProfileSettingsTransactionCategoriesRoute
  '/p/$profileId/accounts': typeof PProfileIdProfileAccountsIndexRoute
  '/p/$profileId/charts': typeof PProfileIdProfileChartsIndexRoute
  '/p/$profileId/settings': typeof PProfileIdProfileSettingsIndexRoute
  '/p/$profileId/transactions': typeof PProfileIdProfileTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$profileId': typeof PProfileIdProfileIndexRoute
  '/p/$profileId/settings/backup': typeof PProfileIdProfileSettingsBackupRoute
  '/p/$profileId/settings/symbols': typeof PProfileIdProfileSettingsSymbolsRoute
  '/p/$profileId/settings/transaction-categories': typeof PProfileIdProfileSettingsTransactionCategoriesRoute
  '/p/$profileId/accounts': typeof PProfileIdProfileAccountsIndexRoute
  '/p/$profileId/charts': typeof PProfileIdProfileChartsIndexRoute
  '/p/$profileId/settings': typeof PProfileIdProfileSettingsIndexRoute
  '/p/$profileId/transactions': typeof PProfileIdProfileTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$profileId': typeof PProfileIdRouteWithChildren
  '/p/$profileId/_profile': typeof PProfileIdProfileRouteWithChildren
  '/p/$profileId/_profile/': typeof PProfileIdProfileIndexRoute
  '/p/$profileId/_profile/settings/backup': typeof PProfileIdProfileSettingsBackupRoute
  '/p/$profileId/_profile/settings/symbols': typeof PProfileIdProfileSettingsSymbolsRoute
  '/p/$profileId/_profile/settings/transaction-categories': typeof PProfileIdProfileSettingsTransactionCategoriesRoute
  '/p/$profileId/_profile/accounts/': typeof PProfileIdProfileAccountsIndexRoute
  '/p/$profileId/_profile/charts/': typeof PProfileIdProfileChartsIndexRoute
  '/p/$profileId/_profile/settings/': typeof PProfileIdProfileSettingsIndexRoute
  '/p/$profileId/_profile/transactions/': typeof PProfileIdProfileTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$profileId'
    | '/p/$profileId/'
    | '/p/$profileId/settings/backup'
    | '/p/$profileId/settings/symbols'
    | '/p/$profileId/settings/transaction-categories'
    | '/p/$profileId/accounts'
    | '/p/$profileId/charts'
    | '/p/$profileId/settings'
    | '/p/$profileId/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$profileId'
    | '/p/$profileId/settings/backup'
    | '/p/$profileId/settings/symbols'
    | '/p/$profileId/settings/transaction-categories'
    | '/p/$profileId/accounts'
    | '/p/$profileId/charts'
    | '/p/$profileId/settings'
    | '/p/$profileId/transactions'
  id:
    | '__root__'
    | '/'
    | '/p/$profileId'
    | '/p/$profileId/_profile'
    | '/p/$profileId/_profile/'
    | '/p/$profileId/_profile/settings/backup'
    | '/p/$profileId/_profile/settings/symbols'
    | '/p/$profileId/_profile/settings/transaction-categories'
    | '/p/$profileId/_profile/accounts/'
    | '/p/$profileId/_profile/charts/'
    | '/p/$profileId/_profile/settings/'
    | '/p/$profileId/_profile/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProfileIdRoute: typeof PProfileIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$profileId': {
      id: '/p/$profileId'
      path: '/p/$profileId'
      fullPath: '/p/$profileId'
      preLoaderRoute: typeof PProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$profileId/_profile': {
      id: '/p/$profileId/_profile'
      path: '/p/$profileId'
      fullPath: '/p/$profileId'
      preLoaderRoute: typeof PProfileIdProfileRouteImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/_profile/': {
      id: '/p/$profileId/_profile/'
      path: '/'
      fullPath: '/p/$profileId/'
      preLoaderRoute: typeof PProfileIdProfileIndexRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
    '/p/$profileId/_profile/transactions/': {
      id: '/p/$profileId/_profile/transactions/'
      path: '/transactions'
      fullPath: '/p/$profileId/transactions'
      preLoaderRoute: typeof PProfileIdProfileTransactionsIndexRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
    '/p/$profileId/_profile/settings/': {
      id: '/p/$profileId/_profile/settings/'
      path: '/settings'
      fullPath: '/p/$profileId/settings'
      preLoaderRoute: typeof PProfileIdProfileSettingsIndexRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
    '/p/$profileId/_profile/charts/': {
      id: '/p/$profileId/_profile/charts/'
      path: '/charts'
      fullPath: '/p/$profileId/charts'
      preLoaderRoute: typeof PProfileIdProfileChartsIndexRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
    '/p/$profileId/_profile/accounts/': {
      id: '/p/$profileId/_profile/accounts/'
      path: '/accounts'
      fullPath: '/p/$profileId/accounts'
      preLoaderRoute: typeof PProfileIdProfileAccountsIndexRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
    '/p/$profileId/_profile/settings/transaction-categories': {
      id: '/p/$profileId/_profile/settings/transaction-categories'
      path: '/settings/transaction-categories'
      fullPath: '/p/$profileId/settings/transaction-categories'
      preLoaderRoute: typeof PProfileIdProfileSettingsTransactionCategoriesRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
    '/p/$profileId/_profile/settings/symbols': {
      id: '/p/$profileId/_profile/settings/symbols'
      path: '/settings/symbols'
      fullPath: '/p/$profileId/settings/symbols'
      preLoaderRoute: typeof PProfileIdProfileSettingsSymbolsRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
    '/p/$profileId/_profile/settings/backup': {
      id: '/p/$profileId/_profile/settings/backup'
      path: '/settings/backup'
      fullPath: '/p/$profileId/settings/backup'
      preLoaderRoute: typeof PProfileIdProfileSettingsBackupRouteImport
      parentRoute: typeof PProfileIdProfileRoute
    }
  }
}

interface PProfileIdProfileRouteChildren {
  PProfileIdProfileIndexRoute: typeof PProfileIdProfileIndexRoute
  PProfileIdProfileSettingsBackupRoute: typeof PProfileIdProfileSettingsBackupRoute
  PProfileIdProfileSettingsSymbolsRoute: typeof PProfileIdProfileSettingsSymbolsRoute
  PProfileIdProfileSettingsTransactionCategoriesRoute: typeof PProfileIdProfileSettingsTransactionCategoriesRoute
  PProfileIdProfileAccountsIndexRoute: typeof PProfileIdProfileAccountsIndexRoute
  PProfileIdProfileChartsIndexRoute: typeof PProfileIdProfileChartsIndexRoute
  PProfileIdProfileSettingsIndexRoute: typeof PProfileIdProfileSettingsIndexRoute
  PProfileIdProfileTransactionsIndexRoute: typeof PProfileIdProfileTransactionsIndexRoute
}

const PProfileIdProfileRouteChildren: PProfileIdProfileRouteChildren = {
  PProfileIdProfileIndexRoute: PProfileIdProfileIndexRoute,
  PProfileIdProfileSettingsBackupRoute: PProfileIdProfileSettingsBackupRoute,
  PProfileIdProfileSettingsSymbolsRoute: PProfileIdProfileSettingsSymbolsRoute,
  PProfileIdProfileSettingsTransactionCategoriesRoute:
    PProfileIdProfileSettingsTransactionCategoriesRoute,
  PProfileIdProfileAccountsIndexRoute: PProfileIdProfileAccountsIndexRoute,
  PProfileIdProfileChartsIndexRoute: PProfileIdProfileChartsIndexRoute,
  PProfileIdProfileSettingsIndexRoute: PProfileIdProfileSettingsIndexRoute,
  PProfileIdProfileTransactionsIndexRoute:
    PProfileIdProfileTransactionsIndexRoute,
}

const PProfileIdProfileRouteWithChildren =
  PProfileIdProfileRoute._addFileChildren(PProfileIdProfileRouteChildren)

interface PProfileIdRouteChildren {
  PProfileIdProfileRoute: typeof PProfileIdProfileRouteWithChildren
}

const PProfileIdRouteChildren: PProfileIdRouteChildren = {
  PProfileIdProfileRoute: PProfileIdProfileRouteWithChildren,
}

const PProfileIdRouteWithChildren = PProfileIdRoute._addFileChildren(
  PProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProfileIdRoute: PProfileIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
